mm:
	gcc -std=c11 -Wall -Werror -g mm.c -lm -o $@

racer:
	gcc -std=c11 -Wall -Werror -g racer.c -lm -o $@

isolation1:
	gcc -std=c11 -Wall -Werror -g isolation1.c -lm -o $@

cheese:
	gcc -std=c11 -Wall -Werror -g cheesefactory.c -lm -o $@

cheese1:
	gcc -std=c11 -Wall -Werror -g cheesefactory1.c -lm -o $@